version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
          timezone: "Asia/India"
          time: "09:00"
      labels:
          - "npm"
          - "dependencies"

      commit-message:
          prefix: "pip prod"
          prefix-development: "pip dev"
          include: "scope"
