name: Saints for Us

on:
    pull_request:
        branches: [main]

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v3
              with:
                  python-version: "3.x"
            - run: python main.py
